camera0: 4 # logitech: 1920x1080
camera1: 6 # logitech: 1920x1080
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 2
checkerboard_box_size_scale : 10.0
checkerboard_rows: 7
checkerboard_columns: 6
cooldown: 100
